name: ios

on: [push]

jobs:
  tests:
    runs-on: ubuntu
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install node modules
        run: |
          yarn install
      - name: Run tests
        run: |
          yarn test
  deploy:
    runs-on: macos-latest
    needs: tests
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install node modules
        run: |
          yarn install
      - name: Set environment variables from project settings
        working-directory: ./ios
        run: |
          exec ../.github/scripts/set-env-from-xcodeproj.sh
      - name: Import signing certificate
        env:
          SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
        run: |
          exec .github/scripts/import-certificate.sh
      - name: Import provisioning profile
        env:
          PROVISIONING_PROFILE_DATA: ${{ secrets.PROVISIONING_PROFILE_DATA }}
        run: |
          exec .github/scripts/import-profile.sh
      - name: Cache CocoaPods
        uses: actions/cache@v1
        with:
          path: ios/Pods
          key: ${{ runner.OS }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-pods-
      - name: Update Pods
        working-directory: ./ios
        run: |
          gem update cocoapods xcodeproj
          pod install
      - name: Build app
        run: |
          fastlane gym --scheme "ReactNativeGithubActions" --workspace "./ios/ReactNativeGithubActions.xcworkspace"
      - name: run number with offset
        env:
          NUM: ${{ github.run_number }}
        run: |
          echo ::set-env name=MANUAL_GITHUB_RUN_NUMBER::$(($NUM))

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.MANUAL_GITHUB_RUN_NUMBER }}
          name: Build ${{ env.MANUAL_GITHUB_RUN_NUMBER }}
          files: |
            ${{ env.PRODUCT_NAME }}.ipa
            ${{ env.PRODUCT_NAME }}.app.dSYM.zip

